
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_clk 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_rst_n 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_tx_point_sweep_test_en 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_tx_point_sweep_test 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/RXCKSB 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/RXDATASB 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_pattern_detected 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/TXDATASB 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_pattern_time_out 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/TXCKSB 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_tx_point_sweep_test_en 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_tx_point_sweep_test 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_lp_linkerror 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_start_training_rdi 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_go_to_phyretrain_ACTIVE 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_reciever_ref_voltage 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_tx_point_test_ack 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_rx_point_test_ack 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_tx_lanes_result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_rx_lanes_result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_selfcal_done_ack 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_rx_cal_done_ack 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_reset_resolved_state 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_time_out 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_start_receiving_pattern 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_start_pattern_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_ACTIVE_DONE 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_LINKINIT_DONE 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_logged_val_result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_logged_lane_id_result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_valid_framing_error 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_REVERSAL_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_CLK_Track_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_LaneID_Pattern_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_logged_clk_result 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/i_VAL_Pattern_done 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Clear_Pattern_Comparator 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Functional_Lanes_out_tx 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Functional_Lanes_out_rx 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Final_ClockMode 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Final_ClockPhase 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_enable_cons 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_clear_clk_detection 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_timeout_disable 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_reciever_ref_voltage 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_pi_step 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_tx_mainband_or_valtrain_test 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_rx_mainband_or_valtrain_test 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_rx_pt_en 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_tx_eye_width_sweep_en 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_curret_operating_speed 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/o_pl_trainerror 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_tx_data_valid 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_msg_valid 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_sub_state 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_msg_no 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_state 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_msg_info 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_is_data_bus 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_start_pattern_req 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_os_msg_valid 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_os_msg_no 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_os_msg_info 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_os_data 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_os_sb_busy 
add wave -group DIE_0 sim:/ltsm_with_sideband_tb/die0_dut/w_sb_pattern_detect_done_rx


add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/RESET 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/FINISH_RESET 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/SBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/LINKINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/ACTIVE 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/PHYRETRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/TRAINERROR_HS 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/COUNT_4ms 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/COUNT_8ms 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_clk 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rst_n 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_lp_linkerror 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_start_training_rdi 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_go_to_phyretrain_ACTIVE 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_reciever_ref_voltage 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_tx_point_test_ack 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_point_test_ack 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_tx_lanes_result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_lanes_result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_selfcal_done_ack 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_cal_done_ack 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_reset_resolved_state 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_time_out 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_decoded_SB_msg 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_sb_busy 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_msg_valid 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_msg_info 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_rx_data_bus 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_start_receiving_pattern 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_start_pattern_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_ACTIVE_DONE 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_LINKINIT_DONE 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_logged_val_result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_logged_lane_id_result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_valid_framing_error 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_REVERSAL_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_CLK_Track_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_LaneID_Pattern_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_logged_clk_result 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_VAL_Pattern_done 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_encoded_SB_msg 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_msg_valid 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_state 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_sub_state 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_data_bus 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_msg_info 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_data_valid 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_start_pattern_req 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Clear_Pattern_Comparator 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Functional_Lanes_out_tx 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Functional_Lanes_out_rx 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Final_ClockMode 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Final_ClockPhase 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_enable_cons 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_clear_clk_detection 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_timeout_disable 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_reciever_ref_voltage 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_pi_step 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_mainband_or_valtrain_test 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_rx_mainband_or_valtrain_test 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_rx_pt_en 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_tx_eye_width_sweep_en 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_curret_operating_speed 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/o_pl_trainerror 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sub_state_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_tx_Functional_Lanes_out 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_rx_Functional_Lanes_out 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_tx_Functional_Lanes_out 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_rx_Functional_Lanes_out 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/w_Final_MaxDataRate 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/w_resolved_state 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/w_phyretrain_error_encoding 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/encoded_SB_msg_SBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/encoded_SB_msg_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/encoded_SB_msg_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/encoded_SB_msg_PHYRETRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/encoded_SB_msg_TRAINERROR 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_info_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_info_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_info_PHYRETRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_valid_SBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_valid_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_valid_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_valid_PHYRETRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/msg_valid_TRAINERROR 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/enter_from_active_or_mbtrain 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/go_to_trainerror_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/SBINIT_EN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_EN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/PHYRETRAIN_EN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_EN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/TRAINERROR_EN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/SBINIT_END 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_END 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/PHYRETRAIN_END 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_END 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/TRAINERROR_END 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/go_to_phyretrain_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/trainerror_condition 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/reset_counter 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/timeout_counter 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/start_reset_counter 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/counter_reset_flag 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/i_busy_reg 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/w_falling_edg_busy 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_Vref 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sub_state_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/CS 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/NS 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/state_timeout 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/reg_sub_state_MBINIT 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/reg_sub_state_MBTRAIN 
add wave -group DIE_0_ltsm sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/reset_state_timeout_counter




add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/SB_MSG_WIDTH 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_clk 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_rst_n 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_SBINIT_en 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_start_pattern_done 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_rx_msg_valid 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_sb_busy 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/i_decoded_SB_msg 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/o_encoded_SB_msg 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/o_tx_msg_valid 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/o_start_pattern_req 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/o_SBINIT_end 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_encoded_msg 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_valid 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_start_pattern_req 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_SBINIT_end 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_encoded_msg 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_valid 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_SBINIT_end 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_ready 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_ready 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/sb_ready 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/grant 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/grant_tx 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/grant_rx 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/fire_tx 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/fire_rx 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/fire_any 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/tx_done_seen 
add wave -group DIE_0_sbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/sbinit_wrapper_dut/rx_done_seen



 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/CLK 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/rst_n 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_MBINIT_Start_en 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_rx_msg_no 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_rx_data_bus 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_rx_msg_info 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_rx_busy 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_falling_edge_busy 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_msg_valid 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_REVERSAL_done 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_CLK_Track_done 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_VAL_Pattern_done 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_LaneID_Pattern_done 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_logged_clk_result 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_logged_val_result 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_logged_lane_id_result 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_sub_state 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_bus 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_info 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_valid 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Clear_Pattern_Comparator 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Functional_Lanes_out_tx 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Functional_Lanes_out_rx 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Final_MaxDataRate 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Final_ClockMode 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Final_ClockPhase 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_train_error_req 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_enable_cons 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_clear_clk_detection 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_Finish_MBINIT 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/param_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/cal_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/repairclk_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/repairval_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/reversalmb_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/repairmb_start 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_PARAM_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_CAL_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_REPAIRCLK_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_REPAIRVAL_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_REVERSALMB_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/MBINIT_REPAIRMB_end 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_param 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_CAL 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_REPAIRCLK 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_REPAIRVAL 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_REVERSALMB 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_valid_REPAIRMB 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_param 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_cal 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_repairclk 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_repairval 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_reversalmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_no_repairmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_bus_param 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_bus_reversalmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_valid_param 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_data_valid_reversalmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_info_repairclk 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_tx_msg_info_repairval 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_msg_info_repairmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/train_error_req_param 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/train_error_req_repairclk 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/train_error_req_repairval 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/train_error_req_repairmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/o_train_error_req_reversalmb 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/Functional_Lanes_out_tx 
add wave -group DIE_0_mbinit  sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBINIT_dut/Functional_Lanes_out_rx



add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/clk 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/rst_n 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_sideband_message 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_sideband_data 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_falling_edge_busy 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_sideband_valid 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_sideband_data_lanes_encoding 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_tx_point_test_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_rx_point_test_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_tx_lanes_result 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_rx_lanes_result 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_tx_valid_result 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_selfcal_done_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_rx_cal_done_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_valid_framing_error 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_phyretrain_resolved_state 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_highest_common_speed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_first_8_tx_lanes_are_functional_mbinit 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_second_8_tx_lanes_are_functional_mbinit 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_first_8_rx_lanes_are_functional_mbinit 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_second_8_rx_lanes_are_functional_mbinit 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_reciever_ref_voltage 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_substate 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_data_lanes_encoding 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_timeout_disable 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_reciever_ref_voltage 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_pi_step 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_lfsr_or_perlane 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_rx_mainband_or_valtrain_test 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_pt_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_rx_pt_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_eye_width_sweep_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valvref_lane_mask 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_phyretrain_error_encoding 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_mbtrain_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_first_8_tx_lanes_are_functional 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_second_8_tx_lanes_are_functional 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_first_8_rx_lanes_are_functional 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_second_8_rx_lanes_are_functional 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_phyretrain_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_curret_operating_speed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_center_fail 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_center_lane_mask 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_selfcal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_selfcal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_selfcal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_selfcal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_vref_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_vref_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_vref_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_vref_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_pt_en_vref_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_pt_en_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test_train_center_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_rx_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_rx_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_rx_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_rx_cal 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_remote_partner_first_8_lanes_result_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_remote_partner_second_8_lanes_result_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_en_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_sideband_message_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valid_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_test_ack_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_phy_retrain_req_was_sent_or_received 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_error_req_was_sent_or_received 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_speed_degrade_req_was_sent_or_received 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_repair_req_was_sent_or_received 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_local_first_8_lanes_are_functional_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_local_second_8_lanes_are_functional_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_pt_en_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test_linkspeed 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_valvref_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_data_vref_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_speed_idle_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_tx_self_cal_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_rx_clk_cal_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_val_train_center_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_val_train_vref_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_data_train_center_1_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_data_train_vref_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_rx_deskew_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_data_train_center_2_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_link_speed_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/i_repair_ack 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_valvref_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_data_vref_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_speed_idle_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_tx_self_cal_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_rx_clk_cal_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_val_train_center_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_val_train_vref_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_data_train_center_1_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_data_train_vref_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_rx_deskew_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_data_train_center_2_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_link_speed_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_repair_en 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_mux_sel 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_comming_from_repair 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_mainband_or_valtrain_test_controller 
add wave -group DIE_0_mbtrain   sim:/ltsm_with_sideband_tb/die0_dut/ltsm_dut/MBTRAIN_dut/o_rx_cal_en



add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/IDLE 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/PATTERN_GEN 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/START_ENCODE 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/START_FRAMING 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/FINISH 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_clk 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_rst_n 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_start_pattern_req 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_start_pattern_done 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_msg_valid 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_data_valid 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_header_done 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_data_done 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_packet_done 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_SB_busy 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_msg_with_data 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_iteration_finished 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_fifo_empty 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/i_fifo_full 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/o_header_encoder_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/o_data_encoder_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/o_frame_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/o_pattern_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/o_sb_busy 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/CS 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/NS 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/encoder_header_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/encoder_data_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/frame_enable 
add wave -group DIE_0_sb_sb_controller sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/controller_dut/idle_flag_counter
 

  
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/i_clk 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/i_rst_n 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/i_start_pattern_req 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/i_pattern_detected 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/i_ser_done 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/o_start_pattern_done 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/o_pattern_time_out 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/o_pattern 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/o_pattern_valid 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/more_four_ittr_cntr 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/more_four_ittr_cntr_en 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/one_ms_counter 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/one_ms_counter_en 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/send_pattern 
add wave -group DIE_0_sb_sb_pattern_gen sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/pattern_dut/eight_ms_counter

add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_clk 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_clk_div8 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_rst_n 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_write_enable 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_read_enable 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_data_in 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_data_out 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_empty 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_ser_done_sampled 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_full 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_data_valid 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/memory 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/write_count 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/read_count 
add wave -group DIE_0_sb_fifo sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_empty_comb

  
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/SBINIT 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/MBINIT 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/MBTRAIN 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/PHYRETRAIN 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/TRAINERROR 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/PARAM 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/CAL 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/REPAIRCLK 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/REPAIRVAL 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/REVERSALMB 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/REPAIRMB 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/VALREF 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/DATAVREF 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/SPEEDIDLE 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/TXSELFCAL 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/RXCLKCAL 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/VALTRAINCENTER 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/VALTRAINVREF 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/DATATRAINCENTER1 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/DATATRAINVREF 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/RXDESKEW 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/DATATRAINCENTER2 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/LINKSPEED 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/REPAIR 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/TX_INIT_POINT_TEST 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/TX_INIT_SWEEP_TEST 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/RX_INIT_POINT_TEST 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/RX_INIT_SWEEP_TEST 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_clk 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_rst_n 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_data_valid 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_msg_valid 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_header_encoder_enable 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_state 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_sub_state 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_msg_no 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_msg_info 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/o_header_message_encoded 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/o_header_done 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_tx_point_sweep_test_en 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/i_tx_point_sweep_test 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/opcode 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/MsgSubcode 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/MsgCode 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/MsgInfo 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/srcid 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/dstid 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/RX_INIT_D_TO_C_SWEEP_DONE_WITH_RESULTS_MSG 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/TX_OR_RX_INT_D_TO_C_RESULTS_RESP 
add wave -group DIE_0_sb_header_en sim:/ltsm_with_sideband_tb/die0_dut/sb_dut/tx_wrapper_dut/header_d/enable_test



#############die1


add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_clk 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_rst_n 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_tx_point_sweep_test_en 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_tx_point_sweep_test 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/RXCKSB 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/RXDATASB 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_pattern_detected 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/TXDATASB 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_pattern_time_out 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/TXCKSB 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_tx_point_sweep_test_en 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_tx_point_sweep_test 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_lp_linkerror 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_start_training_rdi 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_go_to_phyretrain_ACTIVE 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_reciever_ref_voltage 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_tx_point_test_ack 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_rx_point_test_ack 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_tx_lanes_result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_rx_lanes_result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_selfcal_done_ack 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_rx_cal_done_ack 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_reset_resolved_state 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_time_out 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_start_receiving_pattern 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_start_pattern_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_ACTIVE_DONE 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_LINKINIT_DONE 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_logged_val_result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_logged_lane_id_result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_valid_framing_error 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_REVERSAL_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_CLK_Track_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_LaneID_Pattern_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_logged_clk_result 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/i_VAL_Pattern_done 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Clear_Pattern_Comparator 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Functional_Lanes_out_tx 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Functional_Lanes_out_rx 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Final_ClockMode 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Final_ClockPhase 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_enable_cons 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_clear_clk_detection 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_timeout_disable 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_reciever_ref_voltage 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_pi_step 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_tx_mainband_or_valtrain_test 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_rx_mainband_or_valtrain_test 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_rx_pt_en 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_tx_eye_width_sweep_en 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_curret_operating_speed 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/o_pl_trainerror 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_tx_data_valid 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_msg_valid 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_sub_state 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_msg_no 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_state 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_msg_info 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_is_data_bus 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_start_pattern_req 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_os_msg_valid 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_os_msg_no 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_os_msg_info 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_os_data 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_os_sb_busy 
add wave -group DIE_1 sim:/ltsm_with_sideband_tb/die1_dut/w_sb_pattern_detect_done_rx




add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/RESET 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/FINISH_RESET 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/SBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/LINKINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/ACTIVE 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/PHYRETRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/TRAINERROR_HS 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/COUNT_4ms 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/COUNT_8ms 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_clk 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rst_n 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_lp_linkerror 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_start_training_rdi 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_go_to_phyretrain_ACTIVE 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_reciever_ref_voltage 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_tx_point_test_ack 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_point_test_ack 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_tx_lanes_result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_lanes_result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_selfcal_done_ack 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_cal_done_ack 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_reset_resolved_state 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_time_out 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_decoded_SB_msg 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_sb_busy 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_msg_valid 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_msg_info 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_rx_data_bus 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_start_receiving_pattern 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_start_pattern_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_ACTIVE_DONE 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_LINKINIT_DONE 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_logged_val_result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_logged_lane_id_result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_valid_framing_error 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_REVERSAL_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_CLK_Track_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_LaneID_Pattern_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_logged_clk_result 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_VAL_Pattern_done 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_encoded_SB_msg 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_msg_valid 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_state 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_sub_state 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_data_bus 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_msg_info 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_data_valid 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_start_pattern_req 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Clear_Pattern_Comparator 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Functional_Lanes_out_tx 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Functional_Lanes_out_rx 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Final_ClockMode 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Final_ClockPhase 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_enable_cons 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_clear_clk_detection 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_timeout_disable 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_reciever_ref_voltage 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_pi_step 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_mainband_or_valtrain_test 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_rx_mainband_or_valtrain_test 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_rx_pt_en 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_tx_eye_width_sweep_en 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_curret_operating_speed 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/o_pl_trainerror 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sub_state_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_tx_Functional_Lanes_out 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_rx_Functional_Lanes_out 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_tx_Functional_Lanes_out 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_rx_Functional_Lanes_out 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/w_Final_MaxDataRate 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/w_resolved_state 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/w_phyretrain_error_encoding 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/encoded_SB_msg_SBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/encoded_SB_msg_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/encoded_SB_msg_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/encoded_SB_msg_PHYRETRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/encoded_SB_msg_TRAINERROR 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_info_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_info_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_info_PHYRETRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_valid_SBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_valid_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_valid_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_valid_PHYRETRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/msg_valid_TRAINERROR 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/enter_from_active_or_mbtrain 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/go_to_trainerror_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/SBINIT_EN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_EN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/PHYRETRAIN_EN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_EN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/TRAINERROR_EN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/SBINIT_END 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_END 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/PHYRETRAIN_END 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_END 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/TRAINERROR_END 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/go_to_phyretrain_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/trainerror_condition 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/reset_counter 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/timeout_counter 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/start_reset_counter 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/counter_reset_flag 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_Transmitter_initiated_Data_to_CLK_en 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBINIT_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/i_busy_reg 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/w_falling_edg_busy 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/MBTRAIN_Vref 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sub_state_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/CS 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/NS 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/state_timeout 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/reg_sub_state_MBINIT 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/reg_sub_state_MBTRAIN 
add wave -group DIE_1_ltsm sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/reset_state_timeout_counter
 


add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/SB_MSG_WIDTH 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_clk 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_rst_n 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_SBINIT_en 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_start_pattern_done 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_rx_msg_valid 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_sb_busy 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/i_decoded_SB_msg 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/o_encoded_SB_msg 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/o_tx_msg_valid 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/o_start_pattern_req 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/o_SBINIT_end 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_encoded_msg 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_valid 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_start_pattern_req 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_SBINIT_end 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_encoded_msg 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_valid 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_SBINIT_end 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_tx_ready 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/w_rx_ready 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/sb_ready 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/grant 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/grant_tx 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/grant_rx 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/fire_tx 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/fire_rx 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/fire_any 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/tx_done_seen 
add wave -group DIE_1_sbinit sim:/ltsm_with_sideband_tb/die1_dut/ltsm_dut/sbinit_wrapper_dut/rx_done_seen



add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_clk 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_clk_div8 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_rst_n 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_write_enable 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_read_enable 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/i_data_in 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_data_out 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_empty 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_ser_done_sampled 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_full 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_data_valid 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/memory 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/write_count 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/read_count 
add wave -group DIE_1_fifo  sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/tx_wrapper_dut/FIFO_d/o_empty_comb


  
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/i_clk 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/i_rst_n 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/i_header_decoder_enable 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/i_header_data 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_tx_point_sweep_test_en 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_tx_point_sweep_test 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_msg_no 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_msg_info 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_dec_header_done 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_msg_with_data 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_msg_code_with_data 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/o_msg_sub_code_with_data 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/opcode 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/MsgSubCode 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/MsgCode 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/MsgInfo 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/test_msg 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/sbinit_msg 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/mbinit_msg 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/mbtrain_msg 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/phyretrain_msg 
add wave -group DIE_1_rx_header_en sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/SB_RX_HEADER_DECOEDER_DUT/train_error_msg


add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/i_clk 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/i_clk_pll 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/i_rst_n 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/ser_data_in 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/par_data_out 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/de_ser_done 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/bit_count 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/shift_reg 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/capture_reg 
add wave -group DIE_1_rx_desrealizer sim:/ltsm_with_sideband_tb/die1_dut/sb_dut/RX_WRAPPER_dut/rx_deser_dut/capture_valid