add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_clk
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_rst_n
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_data_valid
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_msg_valid
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_state
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_sub_state
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_msg_no
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_msg_info
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_tx_point_sweep_test_en
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_tx_point_sweep_test
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_data_bus
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_start_pattern_req
add wave -group DIE0 sim:/sb_wrapper_tb/die0_i_pattern_detected
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_sb_busy
add wave -group DIE0 sim:/sb_wrapper_tb/die0_TXDATASB
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_pattern_time_out
add wave -group DIE0 sim:/sb_wrapper_tb/die0_TXCKSB
add wave -group DIE0 sim:/sb_wrapper_tb/die0_RXCKSB

add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_tx_point_sweep_test_en
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_tx_point_sweep_test
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_msg_valid
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_msg_no
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_msg_info
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_data
add wave -group DIE0 sim:/sb_wrapper_tb/die0_o_sb_pattern_detect_done_rx


add wave -group DIE1 sim:/sb_wrapper_tb/die1_RXCKSB
add wave -group DIE1 sim:/sb_wrapper_tb/die1_RXDATASB
add wave -group DIE1 sim:/sb_wrapper_tb/die1_TXCKSB
add wave -group DIE1 sim:/sb_wrapper_tb/die1_TXDATASB
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_data_valid
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_msg_valid
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_state
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_sub_state
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_msg_no
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_msg_info
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_tx_point_sweep_test_en
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_tx_point_sweep_test
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_data_bus
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_start_pattern_req
add wave -group DIE1 sim:/sb_wrapper_tb/die1_i_pattern_detected
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_sb_busy
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_pattern_time_out
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_tx_point_sweep_test_en
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_tx_point_sweep_test
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_msg_valid
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_msg_no
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_msg_info
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_data
add wave -group DIE1 sim:/sb_wrapper_tb/die1_o_sb_pattern_detect_done_rx


add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_clk
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_rst_n
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_data_valid
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_msg_valid
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_state
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_sub_state
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_msg_no
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_msg_info
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_tx_point_sweep_test_en
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_tx_point_sweep_test
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_data_bus
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_start_pattern_req
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/i_pattern_detected
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/o_sb_busy
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/TXDATASB
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/o_pattern_time_out
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/TXCKSB
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_clk_div8
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_header_encoder_enable
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_header_message_encoded
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_header_done
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_data_encoded
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_d_valid
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_packet
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_timeout_ctr_start
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_packet_done
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_start_pattern_done
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_pattern_valid
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_pattern
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_final_packet
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_data_fifo
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_enbale
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_read_enable
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_iteration_finished
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_data_valid
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_busy
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_full
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_data_encoder_enable
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_frame_en
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_start_pattern_req
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_clk_controller
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_empty
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/r_iteration_finished
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/w_msg_with_data
add wave -group DIE0TX sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/o_ser_done_sampled

add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/i_clk
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/RXCKSB
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/i_rst_n
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/RXDATASB
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/i_state
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_tx_point_sweep_test_en
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_tx_point_sweep_test
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_msg_valid
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_msg_no
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_msg_info
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_data
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/o_sb_pattern_detect_done_rx
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_header_done
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_data_done
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_header_enable
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_data_enable
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_de_ser_done
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_deser_data
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_msg_code_with_data
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_msg_sub_code_with_data
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_msg_with_data
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_pkt_valid
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_div_clk
add wave -group DIE0RX sim:/sb_wrapper_tb/die0_dut/RX_WRAPPER_dut/w_data16_valid


add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_clk
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_rst_n
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_data_valid
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_msg_valid
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_state
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_sub_state
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_msg_no
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_msg_info
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_tx_point_sweep_test_en
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_tx_point_sweep_test
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_data_bus
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_start_pattern_req
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/i_pattern_detected
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/o_sb_busy
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/TXDATASB
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/o_pattern_time_out
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/TXCKSB
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_clk_div8
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_header_encoder_enable
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_header_message_encoded
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_header_done
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_data_encoded
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_d_valid
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_packet
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_timeout_ctr_start
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_packet_done
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_start_pattern_done
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_pattern_valid
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_pattern
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_final_packet
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_data_fifo
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_enbale
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_read_enable
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_iteration_finished
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_data_valid
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_busy
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_full
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_data_encoder_enable
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_frame_en
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_start_pattern_req
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_clk_controller
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_empty
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/r_iteration_finished
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/w_msg_with_data
add wave -group DIE1TX sim:/sb_wrapper_tb/die1_dut/tx_wrapper_dut/o_ser_done_sampled

add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/i_clk
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/RXCKSB
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/i_rst_n
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/RXDATASB
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/i_state
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_tx_point_sweep_test_en
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_tx_point_sweep_test
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_msg_valid
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_msg_no
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_msg_info
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_data
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/o_sb_pattern_detect_done_rx
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_header_done
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_data_done
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_header_enable
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_data_enable
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_de_ser_done
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_deser_data
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_msg_code_with_data
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_msg_sub_code_with_data
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_msg_with_data
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_pkt_valid
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_div_clk
add wave -group DIE1RX sim:/sb_wrapper_tb/die1_dut/RX_WRAPPER_dut/w_data16_valid


add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/IDLE 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/PATTERN_GEN 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/START_ENCODE 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/START_FRAMING 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/FINISH 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_clk 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_rst_n 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_start_pattern_req 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_start_pattern_done 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_msg_valid 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_data_valid 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_header_done 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_data_done 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_packet_done 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_SB_busy 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_msg_with_data 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_iteration_finished 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_fifo_empty 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/i_fifo_full 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/o_header_encoder_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/o_data_encoder_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/o_frame_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/o_pattern_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/o_sb_busy 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/CS 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/NS 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/encoder_header_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/encoder_data_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/frame_enable 
add wave -group TX_CONTROLLER_FSM sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/controller_dut/idle_flag_counter

add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_clk 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_rst_n 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_data_valid 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_msg_valid 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_header_encoder_enable 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_state 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_sub_state 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_msg_no 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_msg_info 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/o_header_message_encoded 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/o_header_done 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_tx_point_sweep_test_en 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/i_tx_point_sweep_test 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/opcode 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/MsgSubcode 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/MsgCode 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/MsgInfo 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/srcid 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/dstid 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/RX_INIT_D_TO_C_SWEEP_DONE_WITH_RESULTS_MSG 
add wave -group HEADER_ENCODER sim:/sb_wrapper_tb/die0_dut/tx_wrapper_dut/header_d/TX_OR_RX_INT_D_TO_C_RESULTS_RESP
