add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_clk 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rst_n 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_lp_linkerror 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_training_rdi 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_go_to_phyretrain_ACTIVE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_reciever_ref_voltage 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_tx_point_test_ack 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_point_test_ack 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_tx_lanes_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_lanes_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_data_bus 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_reset_resolved_state 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_time_out 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_decoded_SB_msg 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_sb_busy 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_msg_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_msg_info 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_sb_data 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_receiving_pattern 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_ACTIVE_DONE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_LINKINIT_DONE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_val_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_lane_id_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_valid_framing_error 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_REVERSAL_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_CLK_Track_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_LaneID_Pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_clk_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_VAL_Pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_encoded_SB_msg 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_msg_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_sub_state 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_data_bus 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_msg_info 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_data_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_start_pattern_req 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Clear_Pattern_Comparator 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Functional_Lanes_out_tx 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Functional_Lanes_out_rx 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Final_ClockMode 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Final_ClockPhase 

add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_enable_cons 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_clear_clk_detection 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_timeout_disable 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_reciever_ref_voltage 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_pi_step 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_mainband_or_valtrain_test 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_rx_mainband_or_valtrain_test 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_rx_pt_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_eye_width_sweep_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_curret_operating_speed 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_pl_trainerror 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/CS_tb_wp_ltsm 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/NS_tb_wp_ltsm



add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/clk 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rst_n 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_sideband_message 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_sideband_data 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_falling_edge_busy 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_sideband_valid 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_sideband_data_lanes_encoding 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_tx_point_test_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_rx_point_test_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_tx_lanes_result 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_rx_lanes_result 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_tx_valid_result 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_selfcal_done_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_valid_framing_error 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_phyretrain_resolved_state 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_highest_common_speed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_first_8_tx_lanes_are_functional_mbinit 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_second_8_tx_lanes_are_functional_mbinit 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_first_8_rx_lanes_are_functional_mbinit 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_second_8_rx_lanes_are_functional_mbinit 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_reciever_ref_voltage 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_substate 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_data_lanes_encoding 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_timeout_disable 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_reciever_ref_voltage 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_pi_step 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_lfsr_or_perlane 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_rx_mainband_or_valtrain_test 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_pt_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_rx_pt_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_eye_width_sweep_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valvref_lane_mask 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_phyretrain_error_encoding 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_mbtrain_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_first_8_tx_lanes_are_functional 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_second_8_tx_lanes_are_functional 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_first_8_rx_lanes_are_functional 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_second_8_rx_lanes_are_functional 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_phyretrain_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_curret_operating_speed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_center_fail 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_center_lane_mask 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_selfcal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_selfcal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_selfcal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_selfcal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_vref_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_vref_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_vref_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_vref_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_pt_en_vref_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_pt_en_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test_train_center_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_rx_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_rx_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_rx_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_rx_cal 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_remote_partner_first_8_lanes_result_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_remote_partner_second_8_lanes_result_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_en_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_sideband_message_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valid_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_test_ack_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_phy_retrain_req_was_sent_or_received 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_error_req_was_sent_or_received 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_speed_degrade_req_was_sent_or_received 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_repair_req_was_sent_or_received 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_local_first_8_lanes_are_functional_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_local_second_8_lanes_are_functional_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_pt_en_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_mainband_or_valtrain_test_linkspeed 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_valvref_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_data_vref_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_speed_idle_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_tx_self_cal_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_rx_clk_cal_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_val_train_center_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_val_train_vref_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_data_train_center_1_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_data_train_vref_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_rx_deskew_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_data_train_center_2_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_link_speed_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_repair_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_valvref_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_data_vref_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_speed_idle_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_tx_self_cal_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_rx_clk_cal_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_val_train_center_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_val_train_vref_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_data_train_center_1_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_data_train_vref_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_rx_deskew_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_data_train_center_2_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_link_speed_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_repair_en 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_mux_sel 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_comming_from_repair 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_mainband_or_valtrain_test_controller 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/i_rx_cal_done_ack 
add wave -group MBTRAIN_dut sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/o_rx_cal_en


add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/clk 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/rst_n 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/i_en 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/i_selfcal_done_ack 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/i_decoded_sideband_message 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/i_sideband_valid 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/i_busy_negedge_detected 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/o_sideband_message 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/o_valid 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/o_self_cal_ack 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/o_test_en 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/sb_msg_tx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/valid_tx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/ack_speed_tx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/ack_txself_tx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/sb_msg_rx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/valid_rx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/ack_self_tx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/ack_self_rx 
add wave -group self_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/selfcal_wrapper_inst/o_test_en_rx


add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/clk 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/rst_n 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_en 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_decoded_sideband_message 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_sideband_valid 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_busy_negedge_detected 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_algo_done_ack 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_test_ack 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_rx_lanes_result 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_mainband_or_valtrain_test 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/i_reciever_ref_voltage 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_sideband_message 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_valid 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_pt_en 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_mainband_or_valtrain_test 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_valvref_done 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_valvref_fail 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_valvref_lane_mask 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/o_reciever_ref_voltage 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/sb_msg_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/valid_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/pt_en_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/ack_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/fail_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/mask_tx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/sb_msg_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/valid_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/pt_en_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/vref_word_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/ack_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/fail_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/mask_rx 
add wave -group vref_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/vref_cal_wrapper_inst/mode_tx



add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/clk 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/rst_n 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_en 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_decoded_sideband_message 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_sideband_valid 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_busy_negedge_detected 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_mainband_or_valtrain_test 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_lfsr_or_perlane 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_algo_done_ack 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/i_tx_lanes_result 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_sideband_message 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_valid 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_pt_en 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_mainband_or_valtrain_test 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_pi_step 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_traincenter_ack 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_center_fail 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_center_lane_mask 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/sb_msg_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/valid_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/pt_en_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/pi_step_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/ack_val_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/fail_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/mask_tx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/sb_msg_rx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/valid_rx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/ack_val_rx 
add wave -group train_center_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/train_center_cal_wrapper_inst/o_eye_width_sweep_en


add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/clk 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/rst_n 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/i_en 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/i_rx_cal_done_ack 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/i_decoded_sideband_message 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/i_sideband_valid 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/i_busy_negedge_detected 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/o_sideband_message 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/o_valid 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/o_rx_cal_en 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/o_rx_cal_ack 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/sb_msg_tx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/valid_tx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/ack_clk_tx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/ack_dsk_tx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/pt_en_tx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/pt_en_rx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/sb_msg_rx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/valid_rx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/ack_clk_rx 
add wave -group rx_Cal sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/rx_cal_wrapper_inst/ack_dsk_rx

 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/clk 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/rst_n 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_en 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_sideband_message 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_falling_edge_busy 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_sideband_valid 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_sideband_data_lanes_encoding 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_first_8_lanes_are_functional 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/i_second_8_lanes_are_functional 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_valid 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_sideband_data_lanes_encoding 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_sideband_message 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_remote_partner_first_8_lanes_result 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_remote_partner_second_8_lanes_result 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/o_test_ack 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/sb_msg_tx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/valid_tx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/ack_tx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/enc_tx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/tx_finish 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/rx_finish 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/sb_msg_rx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/valid_rx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/ack_rx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/rem1_rx 
add wave -group repair sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/repair_wrapper_inst/rem2_rx

 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/clk 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/rst_n 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_en 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_sideband_message 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_falling_edge_busy 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_sideband_valid 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_point_test_ack 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_lanes_result 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_valid_framing_error 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_first_8_tx_lanes_are_functional 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_second_8_tx_lanes_are_functional 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/i_comming_from_repair 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_valid 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_sideband_message 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_link_speeed_ack 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_phy_retrain_req_was_sent_or_received 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_error_req_was_sent_or_received 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_speed_degrade_req_was_sent_or_received 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_repair_req_was_sent_or_received 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_phyretrain_error_encoding 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_local_first_8_lanes_are_functional 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_local_second_8_lanes_are_functional 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/o_point_test_en 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/sb_msg_tx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/valid_tx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/ack_tx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/pt_en_tx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/sb_msg_rx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/valid_rx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/ack_rx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/pt_en_rx 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/tx_finish 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/rx_finish

add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/linkspeed_tx_inst/cs 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/linkspeed_tx_inst/ns
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/linkspeed_rx_inst/cs 
add wave -group link_speed sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/linkspeed_wrapper_inst/linkspeed_rx_inst/ns

 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/clk 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/rst_n 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_phyretrain_resolved_state 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_highest_common_speed 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_first_8_tx_lanes_are_functional_mbinit 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_second_8_tx_lanes_are_functional_mbinit 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_first_8_rx_lanes_are_functional_mbinit 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_second_8_rx_lanes_are_functional_mbinit 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_first_8_tx_lanes_are_functional_linkspeed 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_second_8_tx_lanes_are_functional_linkspeed 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_first_8_rx_lanes_are_functional_repair 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_second_8_rx_lanes_are_functional_repair 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_phy_retrain_req_was_sent_or_received 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_error_req_was_sent_or_received 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_speed_degrade_req_was_sent_or_received 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_repair_req_was_sent_or_received 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_valvref_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_data_vref_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_speed_idle_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_tx_self_cal_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_rx_clk_cal_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_val_train_center_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_val_train_vref_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_data_train_center_1_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_data_train_vref_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_rx_deskew_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_data_train_center_2_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_link_speed_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/i_repair_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_valvref_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_data_vref_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_speed_idle_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_tx_self_cal_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_rx_clk_cal_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_val_train_center_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_val_train_vref_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_data_train_center_1_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_data_train_vref_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_rx_deskew_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_data_train_center_2_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_link_speed_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_repair_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_mainband_or_valtrain_test 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_phyretrain_en 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_sideband_substate 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_first_8_tx_lanes_are_functional 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_second_8_tx_lanes_are_functional 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_first_8_rx_lanes_are_functional 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_second_8_rx_lanes_are_functional 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_mux_sel 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_mbtrain_ack 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_comming_from_repair 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/o_curret_operating_speed 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/cs 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/ns 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/repiar_was_done_in_mbinit 
add wave -group controller sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mbtrain_controller_inst/repiar_was_done_in_mbtrain

 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/sel_0 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/sel_1 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/sel_2 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_1 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_2 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_3 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_4 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_5 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/in_6 
add wave -group mux sim:/LTSM_wrapper_tb/dut/MBTRAIN_dut/mux_inst/out

 

add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/SB_MSG_WIDTH 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/GRANT_NONE 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/GRANT_TX 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/GRANT_RX 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_clk 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_rst_n 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_PHYRETRAIN_en 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_enter_from_active_or_mbtrain 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_link_status 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_reset_resolved_state 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_sb_busy 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_rx_msg_valid 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_decoded_SB_msg 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/i_rx_msg_info 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/o_encoded_SB_msg 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/o_tx_msg_valid 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/o_tx_msg_info 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/o_PHYRETRAIN_end 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/o_resolved_state 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_tx_encoded_SB_msg 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_tx_msg_info 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_tx_valid 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_tx_PHYRETRAIN_end 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_rx_encoded_SB_msg 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_rx_resolved_state 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_rx_valid 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/wp_rx_PHYRETRAIN_end 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/w_tx_ready_tx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/w_tx_ready_rx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/sb_ready 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/grant 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/grant_tx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/grant_rx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/fire_tx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/fire_rx 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/fire_any 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/tx_done_seen 
add wave -group phyretrain sim:/LTSM_wrapper_tb/dut/PHYRITRAIN_dut/rx_done_seen
