add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_clk 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rst_n 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_lp_linkerror 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_training_rdi 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_go_to_phyretrain_ACTIVE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_reciever_ref_voltage 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_tx_point_test_ack 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_point_test_ack 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_tx_lanes_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_lanes_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_data_bus 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_reset_resolved_state 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_time_out 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_decoded_SB_msg 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_sb_busy 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_msg_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_rx_msg_info 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_sb_data 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_receiving_pattern 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_start_pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_ACTIVE_DONE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_LINKINIT_DONE 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_Transmitter_initiated_Data_to_CLK_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_Transmitter_initiated_Data_to_CLK_Result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_val_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_lane_id_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_valid_framing_error 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_REVERSAL_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_CLK_Track_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_LaneID_Pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_logged_clk_result 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/i_VAL_Pattern_done 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_encoded_SB_msg 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_msg_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_sub_state 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_data_bus 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_msg_info 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_data_valid 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_start_pattern_req 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REVERSALMB_LaneID_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REVERSALMB_ApplyReversal_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Clear_Pattern_Comparator 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Functional_Lanes_out_tx 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Functional_Lanes_out_rx 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Final_ClockMode 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Final_ClockPhase 

add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_enable_cons 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_clear_clk_detection 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REPAIRCLK_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_MBINIT_REPAIRVAL_Pattern_En 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_Transmitter_initiated_Data_to_CLK_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_lfsr_or_perlane_Transmitter_initiated_Data_to_CLK 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_mainband_Transmitter_initiated_Data_to_CLK 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_timeout_disable 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_reciever_ref_voltage 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_pi_step 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_mainband_or_valtrain_test 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_rx_mainband_or_valtrain_test 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_rx_pt_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_tx_eye_width_sweep_en 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_curret_operating_speed 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/o_pl_trainerror 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/CS_tb_wp_ltsm 
add wave -group TEST_BENCH sim:/LTSM_wrapper_tb/NS_tb_wp_ltsm



add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/SB_MSG_WIDTH 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_clk 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_rst_n 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_SBINIT_en 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_start_pattern_done 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_rx_msg_valid 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_sb_busy 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/i_decoded_SB_msg 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/o_encoded_SB_msg 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/o_tx_msg_valid 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/o_start_pattern_req 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/o_SBINIT_end 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_tx_encoded_msg 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_tx_valid 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_tx_start_pattern_req 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_tx_SBINIT_end 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_rx_encoded_msg 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_rx_valid 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_rx_SBINIT_end 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_tx_ready 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/w_rx_ready 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/sb_ready 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/grant 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/grant_tx 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/grant_rx 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/fire_tx 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/fire_rx 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/fire_any 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/tx_done_seen 
add wave -group SBINIT sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/rx_done_seen





add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SB_MSG_WIDTH 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/IDLE 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/START_SB_PATTERN 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_OUT_OF_RESET 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/WAIT_FOR_SB_BUSY 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_DONE_REQ 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_END 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/ERROR 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_done_req_msg 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_done_resp_msg 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/SBINIT_Out_of_Reset_msg 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_clk 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_rst_n 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_SBINIT_en 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_start_pattern_done 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_rx_msg_valid 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_sb_busy 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_tx_ready_tx 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/i_decoded_SB_msg 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/o_encoded_SB_msg_tx 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/o_start_pattern_req 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/o_SBINIT_end_tx 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/o_valid_tx 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/CS 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/NS 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/send_pattern_req 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/send_out_of_reset 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/send_done_req 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/send_sbinit_end 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/timeout_counter 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/timeout_8ms 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/tx_fire 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/out_of_reset_sent 
add wave -group SBINIT_TX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_TX_SBINIT/done_req_sent



add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/SB_MSG_WIDTH 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/IDLE 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/WAIT_FOR_DONE_REQ 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/SBINIT_DONE_RESP 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/SBINIT_END 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/SBINIT_done_req_msg 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/SBINIT_done_resp_msg 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_clk 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_rst_n 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_SBINIT_en 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_rx_msg_valid 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_sb_busy 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_tx_ready_rx 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/i_decoded_SB_msg 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/o_encoded_SB_msg_rx 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/o_SBINIT_end_rx 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/o_valid_rx 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/CS 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/NS 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/tx_fire 
add wave -group SBINIT_RX sim:/LTSM_wrapper_tb/dut/sbinit_wrapper_dut/U_RX_SBINIT/done_resp_sent